services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: arda_games
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d arda_games"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      db:
          condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/arda_games
      - DEBUG=true
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000 
    volumes:
      - .:/app

volumes:
  postgres_data: